--- #YAML:1.0
name:                Template-Plugin-WikiFormat
version:             0.04
abstract:            TT wrapper for Text::WikiFormat
distribution_type:   module
license:             perl
author:
    - Barbie (barbie@cpan.org)

requires:
  Template:                 2
  Template::Plugin::Filter: 0
  Text::WikiFormat:         0.75
recommends:
  Test::More:               0.45
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
  Test::CPAN::Meta:         0.12
build_requires:
  Test::More:               0.45
  Template::Test:           0

provides:
  Template::Plugin::WikiFormat:
    file:     lib/Template/Plugin/WikiFormat.pm
    version:  0.04
no_index:
  directory:
    - t
    - examples

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0

