--- #YAML:1.0
name:                Template-Plugin-WikiFormat
version:             0.02
abstract:            TT wrapper for Text::WikiFormat
license:             perl
author:              
    - Ivor Williams (ivorw@cpan.org)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Template:                      2
    Template::Plugin::Filter:      0
    Template::Test:                0
    Test::Simple:                  0.44
    Text::WikiFormat:              0.75
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
