--- #YAML:1.0
name:                 Template-Plugin-WikiFormat
version:              0.07
abstract:             TT wrapper for Text::WikiFormat
author:
  - Barbie <barbie@cpan.org>

license:              artistic_2
distribution_type:    module
installdirs:          site

requires:
  perl:                     5.006
  Template:                 2
  Template::Plugin::Filter: 2
  Text::WikiFormat:         0.75
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Template::Test:           2
  Test::More:               0.70

provides:
  Template::Plugin::WikiFormat:
    file:     lib/Template/Plugin/WikiFormat.pm
    version:  0.07
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Template-Plugin-WikiFormat
  repository: http://github.com/barbie/template-plugin-wikiformat

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0

