--- #YAML:1.0
name:                Template-Plugin-WikiFormat
version:             0.01
abstract:            TT wrapper for Text::WikiFormat
license:             ~
author:              
    - Ivor Williams (spamless@nowhere.com)
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Test::Simple:                  0.44
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
